app/assets/javascripts/application.js, app/assets/stylesheets/custom.css.scss, app/controllers/application_controller.rb, app/controllers/static_pages_controller.rb, app/models/user.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb, app/views/static_pages/home.html.erb, config/environments/development.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/locales/en.yml, config/routes.rb, db/migrate/20160826062744_create_users.rb, db/migrate/20160828132727_add_devise_to_users.rb, db/schema.rb, db/seeds.rb
Anh xem giúp em với ạ. Em làm task login-logout, khi add devise gem vào thấy có signup, change pasword, edit profile nên em làm luôn. pull này lên đến 29 file nên mong anh xem xét cho em
=> 74548-login-logout

app/assets/javascripts/books_index.js, app/assets/stylesheets/books.scss, app/controllers/books_controller.rb, app/models/book.rb, app/views/books/_filter_book.html.erb, app/views/books/index.html.erb, config/settings.yml
=> 74591_filter_book

Gemfile, Gemfile.lock, app/assets/javascripts/books_index.js, app/assets/stylesheets/books.scss, app/controllers/books_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/views/books/index.html.erb, config/initializers/kaminari_config.rb
=> 74595_search_book

app/assets/stylesheets/books.scss, app/controllers/admin/books_controller.rb, app/helpers/application_helper.rb, app/views/admin/books/index.html.erb, config/locales/en.yml, config/routes.rb, config/settings.yml
=> 75178_admin_show_book_list

app/assets/javascripts/application.js, app/assets/stylesheets/application.css, app/assets/stylesheets/custom.css.scss, app/assets/stylesheets/static_pages.scss, app/controllers/users_controller.rb, app/models/user.rb, app/views/layouts/_header.html.erb, app/views/users/_show.html.erb, app/views/users/show.html.erb, config/locales/en.yml, config/settings.yml
1. Show user's profile
2. Fix some errors in projects
=> Show user profile and fix js errors

app/assets/javascripts/books_index.js, app/assets/stylesheets/books.scss, app/controllers/books_controller.rb, app/controllers/user_books_controller.rb, app/models/user_book.rb, app/views/books/show.html.erb, app/views/user_books/show.html.erb, app/views/users/show.html.erb, config/locales/en.yml, config/routes.rb
Create review book and rating book
=> 74596-create-review-rating

app/controllers/admin/books_controller.rb, app/views/layouts/application.html.erb, config/locales/en.yml
=> 74609_admin_delete_book

Gemfile, Gemfile.lock, app/assets/javascripts/books.coffee, app/assets/javascripts/books_index.js, app/assets/stylesheets/application.css, app/assets/stylesheets/books.scss, app/assets/stylesheets/custom.css.scss, app/assets/stylesheets/static_pages.scss, app/controllers/user_books_controller.rb, app/models/ability.rb, app/models/book.rb, app/models/user.rb, app/models/user_book.rb, app/views/books/index.html.erb, app/views/layouts/application.html.erb, app/views/users/_show.html.erb, app/views/users/show.html.erb
+ Add Cancancan
+ Mark as Favorite book
=> Mark book as favorited

app/controllers/admin/requests_controller.rb, app/controllers/application_controller.rb, app/views/admin/books/index.html.erb, app/views/admin/requests/index.html.erb, config/locales/en.yml, db/seeds.rb, lib/tasks/admin.rake
75486 add rake task
Edit redirect admin_root_path when admin login success
Add search for page show request list
=> 75486_add_rake_task

app/assets/javascripts/admin/requests_update.js, app/controllers/admin/requests_controller.rb, app/controllers/application_controller.rb, app/views/admin/requests/index.html.erb, config/routes.rb
74614 admin accept reject request
=> 74614_admin_accept_reject_request

app/assets/stylesheets/custom.css.scss, app/controllers/comments_controller.rb, app/models/user_book.rb, app/views/books/show.html.erb, app/views/comments/_comment.html.erb, app/views/shared/_comment_form.html.erb, app/views/user_books/show.html.erb, config/locales/en.yml, config/routes.rb
=> 74598-comment-on-review

app/assets/javascripts/requests_create.js, app/assets/stylesheets/books.scss, app/controllers/requests_controller.rb, app/models/request.rb, app/models/user.rb, app/views/books/show.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20160826064740_create_requests.rb, db/schema.rb
=> 75452_user_request_buy_book

config/initializers/devise.rb, config/schedule.rb, lib/tasks/admin.rake
75789_admin_auto_delete_reques
=> 75789_admin_auto_delete_request

app/controllers/admin/categories_controller.rb, app/views/admin/categories/new.html.erb, app/views/devise/shared/_links.html.erb, config/locales/en.yml, config/routes.rb, config/secrets.yml, db/schema.rb
=> 75508_admin_create_category

app/assets/javascripts/requests_create.js, app/assets/stylesheets/books.scss, app/controllers/requests_controller.rb, app/models/ability.rb, app/models/book.rb, app/models/request.rb, app/views/books/index.html.erb, app/views/requests/index.html.erb, config/locales/en.yml, config/routes.rb
=> 74580_user_list_request

app/assets/stylesheets/books.scss, app/controllers/admin/authors_controller.rb, app/controllers/admin/books_controller.rb, app/controllers/admin/languages_controller.rb, app/controllers/admin/publishers_controller.rb, app/controllers/admin/requests_controller.rb, app/controllers/books_controller.rb, app/controllers/user_books_controller.rb, app/controllers/users_controller.rb, app/views/admin/authors/edit.html.erb, app/views/admin/authors/index.html.erb, app/views/admin/books/index.html.erb, app/views/admin/languages/edit.html.erb, app/views/admin/languages/index.html.erb, app/views/admin/publishers/edit.html.erb, app/views/admin/publishers/index.html.erb, config/locales/en.yml, config/routes.rb, db/schema.rb
- Show list languages, authors, publishers
- Edit languages, authors, publishers
- Delete languages, authors, publishers
- Add cancancan model
- Fix friendly id
=> Show list languages, authors, publishers

Gemfile, Gemfile.lock, spec/models/like_spec.rb, spec/rails_helper.rb, spec/spec_helper.rb
=> RSpec model like

Gemfile, Gemfile.lock, db/schema.rb, spec/factories/category.rb, spec/factories/user.rb, spec/factories/user_book.rb, spec/models/book_spec.rb, spec/spec_helper.rb
=> tet_model_book

app/controllers/books_controller.rb, spec/controllers/books_controller_spec.rb, spec/rails_helper.rb
=> test_controller_book

spec/controllers/comments_controller_spec.rb, spec/factories/comment.rb, spec/factories/user_book.rb, spec/rails_helper.rb
=> test controller-comment

Gemfile, Gemfile.lock, spec/views/users/index.html.erb_spec.rb
=> test_view_user_index
